name = "knowledge-plateform"
main = "worker.ts"
compatibility_date = "2024-09-01"

[assets]
directory = "./dist"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "knowledge-db"
database_id = "05eb5cd0-e10f-4c68-9316-db0128e718c7"
